{% set version = "1.6.8.0" %}
{% set sha256 = "1014bec3735af2bff9ad08e15847da21f8db7c946375afcc07baa5c25d041de0" %}

package:
  name: maxquant
  version: '{{ version }}'

source:
  url: http://share.gruenings.eu/MaxQuant_{{ version }}.zip
  sha256: '{{ sha256 }}'

build:
  number: 0
  skip: True # [osx]
  noarch: generic
  script:
    - cp -r * $PREFIX
    - cp $RECIPE_DIR/maxquant $PREFIX/bin/maxquant
    - chmod +x $PREFIX/bin/maxquant

requirements:
  run:
    - mono >=5.0.0

test:
  commands:
    #- maxquant --version 2> foo.txt ; cat foo.txt
    # It seem that the way conda is running the tests will yield to a crashing maxquant, its works locally if you do not use pipes or subshells
    - which maxquant

about:
  home: http://www.coxdocs.org/doku.php?id=maxquant:start
  license: http://www.coxdocs.org/lib/exe/fetch.php?media=license_agreement.pdf
  summary: |
    MaxQuant is a quantitative proteomics software package designed for analyzing
    large mass-spectrometric data sets. License restricted.
